// Package docs GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/notif": {
            "post": {
                "description": "Add notification to the array of notification",
                "summary": "Add notification to the array of notification",
                "parameters": [
                    {
                        "description": "notification",
                        "name": "Notification",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/routes.AddNotifBody"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/notif/send": {
            "post": {
                "description": "Send notification to the array of notification",
                "summary": "Send notification to the array of notification",
                "parameters": [
                    {
                        "description": "subscription",
                        "name": "Sub",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/routes.SendNotifBody"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/tache": {
            "get": {
                "description": "get all todotask in mongodb",
                "summary": "Allow the user to get all todotask",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.Task"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "create todotask in mongodb",
                "summary": "Allow the user to create todotask",
                "parameters": [
                    {
                        "description": "Label",
                        "name": "Label",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/routes.AddTaskBody"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/tache/{id}": {
            "get": {
                "description": "get one todotask in mongodb",
                "summary": "Allow the user to get one todotask",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Task Id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.Task"
                            }
                        }
                    }
                }
            },
            "put": {
                "summary": "Edit todoTask Label",
                "parameters": [
                    {
                        "description": "Label",
                        "name": "Label",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/routes.EditTitleTaskBody"
                        }
                    },
                    {
                        "type": "string",
                        "description": "Task Id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Task"
                        }
                    }
                }
            },
            "delete": {
                "summary": "Delete todoTask",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Task Id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Task"
                        }
                    }
                }
            }
        },
        "/tache/{id}/change-statut": {
            "put": {
                "summary": "Edit todoTask Status",
                "parameters": [
                    {
                        "description": "Status",
                        "name": "Label",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/routes.ChangeStatusTaskBody"
                        }
                    },
                    {
                        "type": "string",
                        "description": "Task Id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Task"
                        }
                    }
                }
            }
        },
        "/tache/{id}/deadline": {
            "put": {
                "summary": "Edit todoTask DeadLine",
                "parameters": [
                    {
                        "description": "DeadLine",
                        "name": "DeadLine",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/routes.EditDeadLineTaskBody"
                        }
                    },
                    {
                        "type": "string",
                        "description": "Task Id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Task"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "model.Action": {
            "type": "object",
            "properties": {
                "action": {
                    "type": "string"
                },
                "icon": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "model.Notification": {
            "type": "object",
            "properties": {
                "actions": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.Action"
                    }
                },
                "body": {
                    "type": "string"
                },
                "icon": {
                    "type": "string"
                },
                "image": {
                    "type": "string"
                },
                "tag": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "vibrate": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                }
            }
        },
        "model.Task": {
            "type": "object",
            "properties": {
                "DeadLine": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "label": {
                    "type": "string"
                },
                "status": {
                    "type": "boolean"
                }
            }
        },
        "routes.AddNotifBody": {
            "type": "object",
            "properties": {
                "subscription": {
                    "$ref": "#/definitions/webpush.Subscription"
                }
            }
        },
        "routes.AddTaskBody": {
            "type": "object",
            "properties": {
                "deadline": {
                    "type": "string"
                },
                "label": {
                    "type": "string"
                }
            }
        },
        "routes.ChangeStatusTaskBody": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "boolean"
                }
            }
        },
        "routes.EditDeadLineTaskBody": {
            "type": "object",
            "properties": {
                "deadline": {
                    "type": "string"
                }
            }
        },
        "routes.EditTitleTaskBody": {
            "type": "object",
            "properties": {
                "label": {
                    "type": "string"
                }
            }
        },
        "routes.SendNotifBody": {
            "type": "object",
            "properties": {
                "notif": {
                    "$ref": "#/definitions/model.Notification"
                }
            }
        },
        "webpush.Keys": {
            "type": "object",
            "properties": {
                "auth": {
                    "type": "string"
                },
                "p256dh": {
                    "type": "string"
                }
            }
        },
        "webpush.Subscription": {
            "type": "object",
            "properties": {
                "endpoint": {
                    "type": "string"
                },
                "keys": {
                    "$ref": "#/definitions/webpush.Keys"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "Todolist Cloud Deployment",
	Description:      "Api TODO List du cours de virtualisation",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
